import { VocabularyTopic } from '@/types';

export const vocabularyTopics: VocabularyTopic[] = [
  {
    id: 'physics',
    name: 'Physics',
    terms: [
      { term: 'net force' },
      { term: 'acceleration' },
      { term: "Newton's Second Law" },
      { term: 'friction' },
      { term: 'normal force' },
      { term: 'tension' },
      { term: 'gravitational force' },
      { term: 'free body diagram' },
      { term: 'equilibrium' },
      { term: 'inertia' },
      { term: 'velocity' },
      { term: 'momentum' },
      { term: 'kinetic energy' },
      { term: 'potential energy' },
      { term: 'work' },
      { term: 'power' },
      { term: 'wavelength' },
      { term: 'frequency' },
      { term: 'refraction' },
      { term: 'reflection' },
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    terms: [
      { term: 'reactant' },
      { term: 'product' },
      { term: 'catalyst' },
      { term: 'activation energy' },
      { term: 'exothermic' },
      { term: 'endothermic' },
      { term: 'equilibrium constant' },
      { term: 'rate law' },
      { term: 'oxidation' },
      { term: 'reduction' },
      { term: 'molecule' },
      { term: 'atom' },
      { term: 'electron' },
      { term: 'proton' },
      { term: 'neutron' },
      { term: 'periodic table' },
      { term: 'valence' },
      { term: 'ionic bond' },
      { term: 'covalent bond' },
      { term: 'pH' },
    ],
  },
  {
    id: 'biology',
    name: 'Biology',
    terms: [
      { term: 'organism' },
      { term: 'organisms' },
      { term: 'ecology' },
      { term: 'ecosystem' },
      { term: 'food chain' },
      { term: 'producer' },
      { term: 'consumer' },
      { term: 'decomposer' },
      { term: 'habitat' },
      { term: 'photosynthesis' },
      { term: 'cellular respiration' },
      { term: 'mitochondria' },
      { term: 'ribosome' },
      { term: 'cell membrane' },
      { term: 'nucleus' },
      { term: 'ATP' },
      { term: 'osmosis' },
      { term: 'Golgi apparatus' },
      { term: 'endoplasmic reticulum' },
      { term: 'DNA' },
      { term: 'RNA' },
      { term: 'chromosome' },
      { term: 'evolution' },
      { term: 'natural selection' },
      { term: 'biodiversity' },
    ],
  },
  {
    id: 'calculus',
    name: 'Calculus',
    terms: [
      { term: 'derivative' },
      { term: 'limit' },
      { term: 'chain rule' },
      { term: 'product rule' },
      { term: 'quotient rule' },
      { term: 'implicit differentiation' },
      { term: 'critical point' },
      { term: 'inflection point' },
      { term: 'tangent line' },
      { term: 'second derivative' },
      { term: 'integral' },
      { term: 'antiderivative' },
      { term: 'definite integral' },
      { term: 'indefinite integral' },
      { term: 'u-substitution' },
      { term: 'area under the curve' },
      { term: 'related rates' },
      { term: 'optimization' },
      { term: 'Riemann sum' },
      { term: 'fundamental theorem' },
    ],
  },
  {
    id: 'algebra',
    name: 'Algebra',
    terms: [
      { term: 'variable' },
      { term: 'equation' },
      { term: 'inequality' },
      { term: 'linear equation' },
      { term: 'quadratic equation' },
      { term: 'slope' },
      { term: 'y-intercept' },
      { term: 'factor' },
      { term: 'factoring' },
      { term: 'polynomial' },
      { term: 'exponent' },
      { term: 'quadratic formula' },
      { term: 'parabola' },
      { term: 'function' },
      { term: 'domain' },
      { term: 'range' },
      { term: 'system of equations' },
      { term: 'substitution' },
      { term: 'elimination' },
      { term: 'absolute value' },
    ],
  },
  {
    id: 'history',
    name: 'History',
    terms: [
      { term: 'secession' },
      { term: 'Confederacy' },
      { term: 'Emancipation Proclamation' },
      { term: 'abolition' },
      { term: 'Reconstruction' },
      { term: "states' rights" },
      { term: 'Union' },
      { term: 'Gettysburg' },
      { term: 'Antietam' },
      { term: 'Appomattox' },
      { term: 'Revolution' },
      { term: 'Constitution' },
      { term: 'Declaration of Independence' },
      { term: 'colonial' },
      { term: 'industrialization' },
      { term: 'suffrage' },
      { term: 'civil rights' },
      { term: 'Cold War' },
      { term: 'democracy' },
      { term: 'federalism' },
    ],
  },
  {
    id: 'english',
    name: 'English',
    terms: [
      { term: 'metaphor' },
      { term: 'simile' },
      { term: 'personification' },
      { term: 'alliteration' },
      { term: 'theme' },
      { term: 'plot' },
      { term: 'character' },
      { term: 'setting' },
      { term: 'conflict' },
      { term: 'resolution' },
      { term: 'protagonist' },
      { term: 'antagonist' },
      { term: 'irony' },
      { term: 'symbolism' },
      { term: 'tone' },
      { term: 'mood' },
      { term: 'foreshadowing' },
      { term: 'point of view' },
      { term: 'narrator' },
      { term: 'climax' },
    ],
  },
  {
    id: 'geography',
    name: 'Geography',
    terms: [
      { term: 'latitude' },
      { term: 'longitude' },
      { term: 'equator' },
      { term: 'hemisphere' },
      { term: 'climate' },
      { term: 'weather' },
      { term: 'topography' },
      { term: 'plateau' },
      { term: 'peninsula' },
      { term: 'archipelago' },
      { term: 'tributary' },
      { term: 'delta' },
      { term: 'population' },
      { term: 'migration' },
      { term: 'urban' },
      { term: 'rural' },
      { term: 'region' },
      { term: 'continent' },
      { term: 'time zone' },
      { term: 'cartography' },
    ],
  },
  {
    id: 'computer-science',
    name: 'Computer Science',
    terms: [
      { term: 'algorithm' },
      { term: 'variable' },
      { term: 'function' },
      { term: 'loop' },
      { term: 'array' },
      { term: 'string' },
      { term: 'boolean' },
      { term: 'debugging' },
      { term: 'syntax' },
      { term: 'binary' },
      { term: 'API' },
      { term: 'database' },
      { term: 'server' },
      { term: 'client' },
      { term: 'input' },
      { term: 'output' },
      { term: 'conditional' },
      { term: 'recursion' },
      { term: 'data structure' },
      { term: 'programming' },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    terms: [
      { term: 'marketing' },
      { term: 'Four Ps' },
      { term: 'target market' },
      { term: 'market segmentation' },
      { term: 'brand awareness' },
      { term: 'value proposition' },
      { term: 'customer acquisition' },
      { term: 'conversion rate' },
      { term: 'ROI' },
      { term: 'advertising' },
      { term: 'campaign' },
      { term: 'analytics' },
      { term: 'social media' },
      { term: 'SEO' },
      { term: 'demographics' },
      { term: 'competitor' },
      { term: 'pricing' },
      { term: 'promotion' },
      { term: 'distribution' },
      { term: 'customer retention' },
    ],
  },
];

export function getTopicById(id: string): VocabularyTopic | undefined {
  return vocabularyTopics.find(topic => topic.id === id);
}

export function searchTermsInText(text: string, topic: VocabularyTopic): string[] {
  const foundTerms: string[] = [];
  const lowerText = text.toLowerCase();
  
  for (const { term } of topic.terms) {
    if (lowerText.includes(term.toLowerCase())) {
      foundTerms.push(term);
    }
  }
  
  return foundTerms;
}
